spring:
  cloud:
    config:
      server:
        git:
          # Adresa (URL) către repository-ul Git care conține fișierele de configurare
          uri: https://github.com/Mistocarul/lab2-config-repo.git

          # Ramura implicită din repository-ul Git care va fi folosită pentru configurări
          default-label: main

          # Forțează serverul Config să cloneze repository-ul la pornire,
          # astfel încât să aibă cea mai recentă versiune a fișierelor de configurare
          clone-on-start: true

          # Forțează actualizarea (pull) repository-ului local cu cel remote
          # la fiecare cerere de configurare, pentru a menține configurațiile sincronizate
          force-pull: true

server:
  # Portul pe care rulează serverul Spring Cloud Config
  port: 8888

management:
  endpoints:
    web:
      exposure:
        # Specifică ce endpoint-uri de management sunt expuse prin HTTP
        # "health" → verifică starea aplicației
        # "info" → afișează informații despre aplicație (ex: versiune, build)
        # "refresh" → permite reîncărcarea configurărilor fără repornirea serverului
        include: health,info,refresh
