spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/lab2_prod
    username: root
    password: root

app:
  environment: production
  features:
    analytics: false